### ISSUE TITLE
In certain configurations, wordpress posts are not indexed

### ISSUE THREAD

**Issue by libreliodev** [libreliodev/wordpress#20]
@serverfire 

We have the following issues in one client configuration: 
- only 2 pages appear in the sync queue (given that the other posts have not been indexed previously)
- these 2 pages are not indexed when clicking on the sync button

**Comment by libreliodev** [comment]
@serverfire 

I checked the settings in `lift-core.php`, they look fine, although we may change them in the future:

	public static function get_indexed_post_types() {
		return apply_filters( 'lift_indexed_post_types', get_post_types( array( 'public' => true ) ) );
	}

I noticed that unlike the regular `lift-search`, we no longer have logs on the dashboard. Should not we reactivate logs?

![dashboard](https://cloud.githubusercontent.com/assets/3107052/6915172/2e22d0ac-d792-11e4-97dd-e5ddfd8117fb.png)

**Comment by serverfire** [comment]
@libreliodev Log error has fixed with 34262de

**Comment by serverfire** [comment]
@libreliodev I've to see log error for librelio. Please update customer's site with error log bugfix.
Thank you.

**Comment by libreliodev** [comment]
@serverfire 

> Please update customer's site with error log bugfix.

Customer's site has been updated, but log is still not visible. Maybe you can edit directly the php files in WP to check, while keeping track of all your changes.

>> only 2 pages appear in the sync queue (given that the other posts have not been indexed previously)

I have now understood the reason for this. It's because only posts created or modified after plug-in was installed are taken into account.

Now we need to understand why indexation does not work.

**Comment by serverfire** [comment]
@libreliodev 
I tried to figure out what's the problem.
Now i found that problem is in scheduling send_batch and process_queue.
They're not called at all.
I'm trying to find the reason and fix it.

**Comment by serverfire** [comment]
@libreliodev 
I don't have access to `wp-config.php`.
Can you add the following into the begging of that file?
```
define('ALTERNATE_WP_CRON', true);
```

**Comment by libreliodev** [comment]
@serverfire 

> Can you add the following into the begging of that file?
```
define('ALTERNATE_WP_CRON', true);
```

This is not something we can easily ask to customers. Is there an other way of testing? Can you explain the rationale?

**Comment by serverfire** [comment]
@libreliodev 
> Is there an other way of testing? Can you explain the rationale?

I tried to put it in plugin itself. But i got couple of warnings. Where was not related to our plugin.
And after adding this suddenly queue has updated to 103 items.

Apparently main cron process does not work on the customers site. And this define enables the alternative way for processing cron jobs.

http://wordpress.stackexchange.com/questions/147785/wp-schedule-event-not-working

First we should solve wp-cron issue.

**Comment by libreliodev** [comment]
@serverfire 

Thanks for the explanation. We are going to contact the customer.

**Comment by libreliodev** [comment]
@serverfire 

`wp-config.php` has been updated, but this does not seem to fix the issue. Can you check on your side?

**Comment by serverfire** [comment]
@libreliodev I checked. But apparently It's not added yet.
`defined('ALTERNATE_WP_CRON')` return's false.

**Comment by libreliodev** [comment]
@serverfire Sorry, the customer had changed `wp-config.php`on another site. We will keep you posted when we get more info.

**Comment by libreliodev** [comment]
@serverfire Please check again at the new address provided to you privately. Indexing is still not working.

**Comment by serverfire** [comment]
@libreliodev I found the problem. It will take some time to fix it.
Problem is `amazon-web-service` plugin initiates after `init` state. And cron jobs are executing before it.
We might need to change that plugin.

**Comment by libreliodev** [comment]
@serverfire 

Thanks for the feedback. I have 2 questions:

1- Why did not we detect this issue during our tests? could this be because we entered the aws credentials in `wp-config`, whereas the customer entered them in the database?

2- Instead of modifying the `amazon-web-service` plugin, would not it be better to enter the aws credentials directly in our plug-in?

**Comment by serverfire** [comment]
@libreliodev 
>1- Why did not we detect this issue during our tests? could this be because we entered the aws credentials in wp-config, whereas the customer entered them in the database?

Because then cron jobs where not executed at all. No.

>2- Instead of modifying the amazon-web-service plugin, would not it be better to enter the aws credentials directly in our plug-in?

It's not necessary to change `amazon-web-service`. I was able to make it work without change. No problem here.


After fixing this issue. Another one came up. That required defining index fields. I made the changes. And now it's applying the schema. It's wired that it took so long. Nearly 12 hours it's in process.

I'm waiting for the domain to get ready again.

**Comment by libreliodev** [comment]
@serverfire 

> I'm waiting for the domain to get ready again.

I just launched `Run indexing` which was needed for the domain. The current status is now `Processing`. I will keep you posted when it's done.

**Comment by libreliodev** [comment]
@serverfire 

The current status of CouldSearch is now `active`

**Comment by libreliodev** [comment]
@serverfire 

I just made a new test, and got a new error `"Field "taxonomy_post_tag_id" must have array type to have multiple values`.

I changed the index accordingly, and relaunched `Run indexing`

**Comment by libreliodev** [comment]
@serverfire 

Pressing `sync queue now` triggered indexing! Will now make additional tests

**Comment by libreliodev** [comment]
@serverfire 

This issue seems to be fixed. Did you modify the code directly on the client site? Can push the changes to Github?

**Comment by serverfire** [comment]
@libreliodev I was waiting for verification. I'll commit changes in few minutes.

**Comment by serverfire** [comment]
@libreliodev Done.

**Comment by libreliodev** [comment]
@serverfire 

Reopening this issue for a small question: do we still need this?

```
define('ALTERNATE_WP_CRON', true);
```

**Comment by serverfire** [comment]
@libreliodev 
>do we still need this?
define('ALTERNATE_WP_CRON', true);

Yes.

**Comment by libreliodev** [comment]
Thanks
